### ISSUE TITLE
Bad argument #2 to 'remove' (number expected, got table)

### ISSUE THREAD

**Issue by TheStrath** [KirillNaumkin/Teleportation#2]
__Teleportation__/control-telelogistics.lua:96:bad argument #2 to 'remove' (number expected, got table)

When loading a save which had telelogistics enabled with it now disabled.

[Version0.16.1.diff.txt](https://github.com/KirillNaumkin/Teleportation/files/1595530/Version0.16.1.diff.txt)

**Comment by Bilka2** [comment]
This also occurs when entities are otherwise invalidated: https://forums.factorio.com/viewtopic.php?p=393060#p393060

**Comment by KirillNaumkin** [comment]
Fixed a bug. New version will appear after I'll update the mod for 0.17 on the next week. Thanks for the feedback!

**Comment by KirillNaumkin** [comment]
Fixed a bug. New version will appear after I'll update the mod for 0.17 on the next week. Thanks for the feedback!
